name: Daily update

on:
  workflow_dispatch:
  schedule:
    # 北京时间每天晚上 9 点执行
    - cron: '0 13 * * *'

jobs:
  update:
    name: Daily Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.8.1"
      - run: bun install
      - run: bun run fetch
      - run: bun run remake-index
      - run: git config --local user.email "github-actions[bot]@github.com"
      - run: git config --local user.name "github-actions[bot]"
      - run: git add .
      - run: git commit -m "[bot] AUTO UPDATE"
      - name: Push master changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: node18
