name: Daily update

on:
  workflow_dispatch:
  schedule:
    # 北京时间每天上午 9 点执行，获取昨天的数据
    - cron: '0 1 * * *'

jobs:
  update:
    name: Daily Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          with:
            ref: winter
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno task fetch
          deno task make-index
          git config --local user.email "github-actions[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[bot] AUTO UPDATE"
      - name: Push winter branch changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: winter
      - uses: actions/checkout@v4
        with:
          ref: release
      - run: |
          git merge winter
          rm -rf dump_htmls
          git add .
          git commit -m "[bot] RELEASE"
      - name: Push release branch changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

