name: Daily update

on:
  workflow_dispatch:
  schedule:
    # 北京时间每天上午 9 点执行，获取昨天的数据
    - cron: '0 1 * * *'

jobs:
  update:
    name: Daily Sync
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4
        with:
          ref: winter
          fetch-depth: 0
      - name: Setup git
        run: |
          git config --local user.email "github-actions[bot]@github.com"
          git config --local user.name "github-actions[bot]"
      - name: Build
        run: |
          deno task fetch
          deno task make-index
      - name: Commit changes
        run: |
          git add .
          git commit -m "[bot] AUTO UPDATE"
      - name: Push winter branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: winter
